const hasChinese = (value: string) => /[\u3400-\u9fff]/u.test(value)

export const skillChineseNameMap: Record<string, string> = {
  'agent-browser': 'Agent 浏览器自动化',
  'agent-reach': '全网调研与多平台搜索',
  'ai-seo': 'AI 搜索与 GEO 优化',
  'api-and-interface-design': 'API 与接口设计',
  'autumn-campus-defense-ppt': '秋日校园答辩 PPT',
  'baocanmou-ai-skill-center': '包参谋 AI 能力中枢',
  'baocanmou-geo-platform-publisher': '包参谋 GEO 平台发布',
  'baocanmou-wordpress-esa-trust-release': '包参谋网站可信发布',
  baocut: '包剪智能视频工作台',
  'blue-white-3d-tech-ppt': '蓝白 3D 科技商务 PPT',
  'blue-white-minimal-enterprise-ppt': '蓝白极简企业 PPT',
  brandkit: '高端品牌视觉规范',
  'browser-testing-with-devtools': '浏览器开发工具测试',
  'chalkboard-tech-architecture': '黑板粉笔技术架构图',
  'ci-cd-and-automation': '持续集成与自动化',
  'code-review': '代码审查',
  'code-review-and-quality': '代码审查与质量控制',
  'codebase-design': '代码库设计',
  'code-simplification': '代码简化与重构',
  'comic-explainer-illustration': '漫画式说明图',
  'competitive-landscape': '竞争格局分析',
  'competitor-analysis': '竞品 SEO 分析',
  'competitor-profiling': '竞品深度画像',
  'constraint-driven-development': '约束驱动开发',
  'content-strategy': '内容策略规划',
  'context-engineering': '上下文工程',
  'copy-editing': '文案编辑与润色',
  'create-article-visuals': '文章视觉系统生成',
  'customer-research': '客户研究',
  'cyan-circuit-launch-ppt': '青蓝电路发布会 PPT',
  'dark-neon-tech-business-ppt': '暗色霓虹科技商务 PPT',
  dbs: 'DBS 商业工具箱',
  'dbs-action': 'DBS 执行力诊断',
  'dbs-agent-migration': 'DBS Agent 工作台迁移',
  'dbs-ai-check': 'DBS AI 写作特征检测',
  'dbs-benchmark': 'DBS 对标分析',
  'dbs-bridge': 'DBS 多端技能桥接',
  'dbs-chatroom': 'DBS 定向专家聊天室',
  'dbs-chatroom-austrian': 'DBS 奥派经济学聊天室',
  'dbs-content': 'DBS 内容创作诊断',
  'dbs-content-system': 'DBS 内容资产结构化',
  'dbs-decision': 'DBS 个人决策系统',
  'dbs-deconstruct': 'DBS 概念拆解',
  'dbs-diagnosis': 'DBS 商业模式诊断',
  'dbs-goal': 'DBS 目标澄清',
  'dbs-good-question': 'DBS 好问题生成',
  'dbs-hook': 'DBS 内容钩子诊断',
  'dbs-knowledge': 'DBS 知识提取',
  'dbs-learning': 'DBS 学习系统',
  'dbs-report': 'DBS 商业诊断报告',
  'dbs-resonate': 'DBS 共鸣点诊断',
  'dbs-restore': 'DBS 工作现场恢复',
  'dbs-save': 'DBS 工作现场保存',
  'dbs-script-flow': 'DBS 口播脚本流程',
  'dbs-skill-cleaner': 'DBS 技能清理',
  'dbs-slowisfast': 'DBS 慢即是快决策',
  'dbs-spread': 'DBS 传播策略',
  'dbs-update': 'DBS 工具箱更新',
  'dbs-wechat-html': 'DBS 微信公众号排版',
  'dbs-xhs-title': 'DBS 小红书标题生成',
  'debugging-and-error-recovery': '调试与错误恢复',
  defuddle: '网页正文净化提取',
  'deprecation-and-migration': '弃用与迁移治理',
  'design-taste-frontend': '前端设计品味',
  'design-taste-frontend-v1': '前端设计品味旧版',
  'diagnosing-bugs': '缺陷诊断',
  'documentation-and-adrs': '技术文档与架构决策记录',
  'doubt-driven-development': '怀疑驱动开发',
  'ecommerce-visual-copywriting': '电商视觉文案',
  'elegant-chinese-courseware-ppt': '雅致中文课程 PPT',
  eli5: '5 岁也能懂',
  'elon-musk-perspective': '埃隆·马斯克思维视角',
  'embedded-captions': '视频内嵌字幕',
  'engineering-sketch-illustration': '工程草图说明图',
  'faceless-explainer': '无真人出镜解说视频',
  'feynman-perspective': '费曼思维视角',
  figma: 'Figma 设计协作',
  'find-skills': '发现与安装技能',
  'four-panel-comic-explainer-illustration': '四格漫画说明图',
  'frontend-design': '前端界面设计',
  'frontend-ui-engineering': '前端界面工程',
  'full-output-enforcement': '完整输出保障',
  'general-video': '通用视频制作',
  'gimi-illustration': 'GIMI 风格插画',
  'git-workflow-and-versioning': 'Git 工作流与版本管理',
  'gold-orange-business-ppt-infographic': '金橙商务 PPT 信息图',
  'gpt-taste': 'GPT 界面审美顾问',
  'grill-me': '需求追问与方案拷问',
  'grill-with-docs': '基于文档的追问审查',
  grilling: '深度追问',
  'green-rural-industry-ppt-infographic': '绿色乡村产业 PPT 信息图',
  'gsap-core': 'GSAP 核心动画',
  'gsap-frameworks': 'GSAP 框架集成',
  'gsap-performance': 'GSAP 性能优化',
  'gsap-plugins': 'GSAP 插件应用',
  'gsap-react': 'GSAP 与 React 集成',
  'gsap-scrolltrigger': 'GSAP 滚动触发动画',
  'gsap-timeline': 'GSAP 时间轴动画',
  'gsap-utils': 'GSAP 实用工具',
  'guizang-material-illustration': '归藏素材插画',
  'guizang-ppt-skill': '归藏 PPT 设计',
  'guizang-social-card-skill': '归藏社交媒体卡片',
  'handdraw-good-deed-story': '手绘善行故事',
  'high-end-visual-design': '高端视觉设计',
  hyperframes: 'HyperFrames 动态网页视频',
  'hyperframes-animation': 'HyperFrames 动画设计',
  'hyperframes-cli': 'HyperFrames 命令行工具',
  'hyperframes-core': 'HyperFrames 核心开发',
  'hyperframes-creative': 'HyperFrames 创意制作',
  'hyperframes-keyframes': 'HyperFrames 关键帧动画',
  'hyperframes-registry': 'HyperFrames 组件注册表',
  'idea-refine': '创意提炼',
  'identity-skill': '品牌身份系统',
  'image-to-code': '图片转前端代码',
  'imagegen-frontend-mobile': '移动端界面生图',
  'imagegen-frontend-web': '网页界面生图',
  implement: '功能实现',
  impeccable: '前端界面精修',
  'improve-codebase-architecture': '改进代码库架构',
  'incremental-implementation': '增量式实现',
  'industrial-brutalist-ui': '工业粗野主义界面',
  'interview-me': '深度访谈助手',
  'ip-as-logo': 'IP 角色标志设计',
  'iridescent-lavender-glass-ppt': '虹彩薰衣草玻璃 PPT',
  'json-canvas': 'JSON 画布编辑',
  'keyword-clustering': '关键词聚类',
  'keyword-research': '关键词研究',
  last30days: '近 30 天趋势调研',
  'link-prospecting': '外链机会挖掘',
  'logo-generator': '标志创意生成',
  'marketing-plan': '营销计划',
  markitdown: '文档转 Markdown',
  'media-use': '媒体素材使用规范',
  'minimalist-ui': '极简主义界面',
  'mint-watercolor-business-ppt': '薄荷水彩商务 PPT',
  'motion-graphics': '动态图形设计',
  'multicolor-system-architecture-ppt': '多彩系统架构 PPT',
  'music-to-video': '音乐可视化视频',
  'new-chinese-resume-ppt': '新中式简历 PPT',
  'observability-and-instrumentation': '可观测性与监控埋点',
  'obsidian-bases': 'Obsidian 数据库视图',
  'obsidian-cli': 'Obsidian 命令行操作',
  'obsidian-markdown': 'Obsidian Markdown 写作',
  'obsidian-output-sync': 'Obsidian 成果归档同步',
  offers: '产品报价与价值方案',
  'paper-doodle-courseware-ppt': '纸张涂鸦课程 PPT',
  'performance-optimization': '性能优化',
  'planning-and-task-breakdown': '规划与任务拆解',
  'planning-with-files': '基于文件的任务规划',
  'pr-to-video': '代码 PR 转演示视频',
  pricing: '定价策略',
  'product-launch-video': '产品发布视频',
  'product-marketing': '产品营销',
  prototype: '产品原型设计',
  'pure-white-handdrawn-ppt-infographic': '纯白手绘 PPT 信息图',
  'qiaomu-design': '乔木设计顾问',
  'real-office-whiteboard-illustration': '真实办公室白板说明图',
  'red-blue-energy-training-ppt': '红蓝正能量培训 PPT',
  'red-white-corporate-training-ppt': '红白政企培训 PPT',
  'red-white-project-progress-ppt': '红白项目进度汇报 PPT',
  'redesign-existing-projects': '现有产品高级重设计',
  'remotion-to-hyperframes': 'Remotion 转 HyperFrames',
  'rn-bw-text-opener': '黑白文字开场动画',
  'rn-dark-saas-video': '暗色 SaaS 产品视频',
  'rn-motion-director': '动态视频创意导演',
  'rn-motion-replica': '参考视频动效复刻',
  'rn-renhua': '中文技术写作去 AI 味',
  'rn-replica-qc': '视频复刻质量验收',
  'rn-wechat-extract': '微信公众号文章提取',
  'safe-local-batch-ops': '安全本地批量操作',
  'sales-enablement': '销售赋能材料',
  schema: '结构化数据标记',
  'security-and-hardening': '安全加固',
  'seo-audit': 'SEO 全面审计',
  'seo-coach': 'SEO 教练',
  'seo-project-setup': 'SEO 项目初始化',
  'shipping-and-launch': '发布与上线',
  'site-architecture': '网站信息架构',
  'skill-doctor': '技能质量体检',
  'setup-matt-pocock-skills': '配置 Matt Pocock 技能集',
  slideshow: '交互式演示文稿',
  'soft-blue-gold-business-ppt': '浅蓝鎏金商务 PPT',
  'soft-lavender-ppt-infographic': '柔紫商务 PPT 信息图',
  'source-driven-development': '来源驱动开发',
  'spec-driven-development': '规格驱动开发',
  'steve-jobs-perspective': '史蒂夫·乔布斯思维视角',
  'stitch-design-taste': 'Stitch 设计系统',
  'talking-head-recut': '口播视频图形包装',
  'teal-education-courseware-ppt': '青绿教育课程 PPT',
  'tech-bluegreen-ppt-infographic': '科技蓝绿 PPT 信息图',
  'test-driven-development': '测试驱动开发',
  tdd: '测试驱动开发',
  teach: '教学讲解',
  'to-spec': '整理为技术规格',
  triage: '问题分诊',
  'using-agent-skills': 'Agent 技能发现与调用',
  'vercel-react-best-practices': 'Vercel React 最佳实践',
  'visual-explainer': '可视化解释器',
  wayfinder: '代码库导航',
  'web-design-guidelines': '网页设计规范',
  'warm-art-courseware-ppt': '暖黄美术课程 PPT',
  'warm-orange-minimal-ppt-infographic': '暖橙极简 PPT 信息图',
  'whiteboard-handdrawn-explainer-illustration': '白板手绘说明图',
  'yellow-notion-girl-illustration': '黄色 Notion 女孩说明图',
  'yellow-notion-panda-illustration': '黄色 Notion 熊猫说明图',
  'yuwen-publish-precheck': '国内自媒体发布前审查',
}

const tokenTranslations: Record<string, string> = {
  ai: 'AI', api: 'API', agent: 'Agent', agents: 'Agent', skill: '技能', skills: '技能',
  design: '设计', frontend: '前端', backend: '后端', code: '代码', review: '审查',
  quality: '质量', security: '安全', audit: '审计', testing: '测试', browser: '浏览器',
  web: '网页', mobile: '移动端', image: '图片', video: '视频', audio: '音频',
  content: '内容', marketing: '营销', product: '产品', customer: '客户', research: '研究',
  analysis: '分析', strategy: '策略', planning: '规划', optimization: '优化', generator: '生成',
  illustration: '说明图', ppt: 'PPT', infographic: '信息图', workflow: '工作流',
  automation: '自动化', migration: '迁移', documentation: '文档', performance: '性能',
  management: '管理', tool: '工具', tools: '工具', system: '系统', architecture: '架构',
  app: '应用', apps: '应用', article: '文章', assets: '资产', auth: '认证', avatar: '数字人',
  basics: '基础', batch: '批处理', best: '最佳', brand: '品牌', builder: '构建器',
  captions: '字幕', charts: '图表', cli: '命令行', cloud: '云服务', commit: '提交',
  community: '社区', compliance: '合规', compress: '压缩', compute: '计算', connect: '连接',
  context: '上下文', copy: '文案', copywriting: '文案创作', create: '创建', creative: '创意',
  data: '数据', database: '数据库', debug: '调试', debugging: '调试', deploy: '部署',
  development: '开发', diagnostics: '诊断', docs: '文档', edit: '编辑', editing: '编辑',
  email: '邮件', enterprise: '企业', eval: '评测', explainer: '解释器', explore: '探索',
  factory: '工厂', find: '发现', generation: '生成', graphics: '图形', guidelines: '规范',
  handoff: '任务交接', help: '帮助', hosting: '托管', ideas: '创意', implement: '实现',
  implementation: '实现', improve: '改进', instrumentation: '监控埋点', interface: '界面',
  keyframes: '关键帧', language: '语言', launch: '发布', library: '资源库', lookup: '查询',
  mail: '邮件', markup: '标记', media: '媒体', meeting: '会议', minimalist: '极简',
  motion: '动效', music: '音乐', native: '原生', note: '笔记', observability: '可观测性',
  onboard: '接入', openapi: 'OpenAPI', optimize: '优化', orchestration: '编排',
  output: '输出', paper: '论文', patterns: '模式', plan: '方案', plans: '方案',
  practices: '实践', prepare: '准备', prd: '产品需求文档', project: '项目', projects: '项目',
  publish: '发布', qa: '质量保障', registration: '注册', reliability: '可靠性', render: '渲染',
  report: '报告', request: '请求', requesting: '请求', resolver: '解析器', resource: '资源',
  run: '运行', safe: '安全', sales: '销售', scaffold: '脚手架', search: '搜索',
  setup: '配置', shared: '共享', slideshow: '演示文稿', social: '社交媒体', spec: '规格',
  storage: '存储', summary: '摘要', template: '模板', test: '测试', theme: '主题',
  tickets: '工单', transitions: '转场', upgrade: '升级', use: '使用', using: '使用',
  validate: '验证', verification: '验证', visual: '视觉', visualizer: '可视化',
  vocabulary: '术语', website: '网站', whiteboard: '白板', wiki: '知识库', write: '写作',
  writing: '写作', xlsx: 'Excel', zoom: '缩放',
  grill: '追问', triage: '分诊', prototype: '原型', teach: '教学',
  domain: '领域', modeling: '建模', bugs: '缺陷', codebase: '代码库', refactor: '重构',
}

const inferFromTokens = (name: string) => {
  const normalized = name.split(':').at(-1)?.toLowerCase() ?? name.toLowerCase()
  const words = normalized.split(/[-_\s]+/).filter(Boolean)
  const translated = words.map((word) => tokenTranslations[word] ?? word.toUpperCase())
  const translatedCount = words.filter((word) => Boolean(tokenTranslations[word])).length
  if (translatedCount === 0) return `${words.join(' ')} 专项能力`
  return translated.join(' · ')
}

export type SkillDisplayNames = {
  primary: string
  secondary: string | null
  translated: boolean
}

export const getSkillDisplayNames = (
  name: string,
  description?: string | null,
): SkillDisplayNames => {
  void description
  const trimmed = name.trim()
  if (!trimmed || hasChinese(trimmed)) {
    return { primary: trimmed || '未命名能力', secondary: null, translated: false }
  }
  const key = trimmed.toLowerCase()
  return {
    primary: skillChineseNameMap[key] ?? inferFromTokens(key),
    secondary: trimmed,
    translated: true,
  }
}
